-- CREATE TABLE IF NOT EXISTS users (
--     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     user_name VARCHAR(50) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     CONSTRAINT pk_users PRIMARY KEY (user_id),
--     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
-- );

-- CREATE TABLE IF NOT EXISTS items
-- (
--     item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     item_name        VARCHAR(50)                             NOT NULL,
--     item_description VARCHAR(200)                            NOT NULL,
--     available        BOOLEAN                                 NOT NULL,
--     request_id       BIGINT,
--     owner_id         BIGINT                                  NOT NULL,
--     CONSTRAINT pk_items PRIMARY KEY (item_id),
--     CONSTRAINT fk_items_owner_id_to_users FOREIGN KEY (owner_id) REFERENCES users (user_id)
-- );

-- CREATE TABLE IF NOT EXISTS bookings (
--     booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     booker_id BIGINT NOT NULL,
--     item_id BIGINT NOT NULL,
--     start_time TIMESTAMP NOT NULL,
--     end_time TIMESTAMP NOT NULL,
--     status VARCHAR(50) NOT NULL,
--     CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
--     CONSTRAINT fk_bookings_booker_id_to_users FOREIGN KEY(booker_id) REFERENCES users(user_id),
--     CONSTRAINT fk_bookings_item_id_to_items FOREIGN KEY(item_id) REFERENCES items(item_id)
-- );


CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items
(
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name        VARCHAR(255)                            NOT NULL,
    item_description VARCHAR(255)                            NOT NULL,
    available        BOOLEAN                                 NOT NULL,
    request_id       BIGINT,
    owner_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (item_id),
    CONSTRAINT fk_items_owner_id_to_users FOREIGN KEY (owner_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_booker_id_to_users FOREIGN KEY (booker_id) REFERENCES users(user_id),
    CONSTRAINT fk_bookings_item_id_to_items FOREIGN KEY (item_id) REFERENCES items(item_id)
);
